### ISSUE TITLE
Is it safe for update() to take &self?

### ISSUE THREAD

**Issue by oconnor663** [nabijaczleweli/blake-rs#2]
If I'm reading the C code right, it ends up doing an unsynchronized `memcpy` to internal state. What happens if two threads call this function at the same time on the same hash state? Should it take `&mut self` instead?

**Comment by nabijaczleweli** [comment]
It's probably not, I was doing the API as more of can-I-take-nonmut vs should-I-take-nonmut (bad idea).

**Comment by nabijaczleweli** [comment]
Released in [`v2.0.0`](https://github.com/nabijaczleweli/blake-rs/releases/tag/v2.0.0).
